export async function GET() {
  const destinations = [
    {
      id: 1,
      name: "Bali, Indonesia",
      image: "/tropical-bali-beach-with-rice-terraces.jpg",
      category: "beach",
      description:
        "Experience the tropical paradise of Bali with stunning beaches, rice terraces, and vibrant culture.",
      rating: 4.8,
      price: "$899",
      highlights: ["Rice Terraces", "Sacred Temples", "White Sand Beaches", "Surfing Spots", "Nightlife"],
    },
    {
      id: 2,
      name: "Swiss Alps",
      image: "/snow-covered-swiss-alps-mountains.jpg",
      category: "mountains",
      description: "Majestic mountain peaks, charming Alpine villages, and world-class skiing destinations.",
      rating: 4.9,
      price: "$1,299",
      highlights: ["Skiing", "Hiking Trails", "Mountain Views", "Alpine Villages", "Scenic Trains"],
    },
    {
      id: 3,
      name: "Tokyo, Japan",
      image: "/tokyo-city-skyline-neon-lights.jpg",
      category: "city",
      description: "Modern metropolis blending ancient traditions with cutting-edge technology and culture.",
      rating: 4.7,
      price: "$799",
      highlights: ["Temples", "Shopping Districts", "Nightlife", "Street Food", "Tech Innovation"],
    },
    {
      id: 4,
      name: "Santorini, Greece",
      image: "/white-blue-dome-santorini-greece-island-sunset.jpg",
      category: "beach",
      description: "Iconic island with white-washed buildings, stunning sunsets, and crystal-clear waters.",
      rating: 4.9,
      price: "$1,099",
      highlights: ["Sunset Views", "Wine Tasting", "Blue Domes", "Beach Clubs", "Local Cuisine"],
    },
    {
      id: 5,
      name: "New Zealand",
      image: "/new-zealand-milford-sound-mountains-nature.jpg",
      category: "adventure",
      description: "Adventure capital with breathtaking landscapes, hiking, and outdoor activities.",
      rating: 4.8,
      price: "$1,399",
      highlights: ["Hiking", "Bungee Jumping", "Scenic Drives", "Glow Worms", "Adventure Sports"],
    },
    {
      id: 6,
      name: "Paris, France",
      image: "/eiffel-tower-paris-city-lights.jpg",
      category: "city",
      description: "The City of Light with romantic streets, iconic landmarks, and world-class cuisine.",
      rating: 4.7,
      price: "$949",
      highlights: ["Eiffel Tower", "Museums", "Cafes", "Art Scene", "Gardens"],
    },
    {
      id: 7,
      name: "Iceland",
      image: "/iceland-waterfalls-northern-lights-nature.jpg",
      category: "adventure",
      description: "Land of fire and ice with waterfalls, glaciers, and the magical Northern Lights.",
      rating: 4.8,
      price: "$1,199",
      highlights: ["Northern Lights", "Waterfalls", "Glaciers", "Geysers", "Hot Springs"],
    },
    {
      id: 8,
      name: "Maldives",
      image: "/maldives-tropical-islands-clear-water-bungalows.jpg",
      category: "beach",
      description: "Luxury tropical paradise with overwater bungalows, coral reefs, and pristine beaches.",
      rating: 4.9,
      price: "$1,599",
      highlights: ["Snorkeling", "Diving", "Water Sports", "Luxury Resorts", "Marine Life"],
    },
    {
      id: 9,
      name: "Morocco",
      image: "/morocco-marrakech-medina-desert-dunes.jpg",
      category: "culture",
      description: "Exotic blend of cultures with bustling medinas, Sahara desert, and coastal beauty.",
      rating: 4.6,
      price: "$799",
      highlights: ["Desert Tours", "Medinas", "Mountains", "Local Markets", "Cuisine"],
    },
  ]

  return Response.json(destinations)
}
